CREATE TABLE IF NOT EXISTS real_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ds DATETIME NOT NULL,
    Product_ID VARCHAR(255) NOT NULL,
    Store_ID VARCHAR(255) NOT NULL,
    y REAL NOT NULL
    )